org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.caching=true
# org.gradle.java.home=D:/Documents/Tugas-Besar-PCD_AI/pandora_box/jdk-21.0.11
kotlin.jvm.target.validation.mode=warning
android.useAndroidX=true
android.enableJetifier=true
org.gradle.user.home=D:/Gradle